version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # Эти свойства перегружают соответствующие в application.yml
    environment:
      - SPRING_DATA_MONGODB_DATABASE=db
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017

  mongo:
    image: mongo:7.0
    restart: always

  mongo-express:
    image: mongo-express:1.0.2
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

