spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bookhub1

  shell:
    interactive:
      enabled: false
    noninteractive:
      enabled: false

    command:
      version:
        enabled: false

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    root: INFO
  file:
    name: hw16_log.txt

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

task:
  book:
    auto-create:
      enable: true