spring:
  datasource:
    url: jdbc:h2:mem:maindb
  jpa:
    show-sql: true
    #    generate-ddl: true
    #    hibernate:
    #      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  shell:
    interactive:
      enabled: false