spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bookhub1

  shell:
    interactive:
      enabled: false
    noninteractive:
      enabled: false

    command:
      version:
        enabled: false

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    root: INFO
  file:
    name: log/hw17_log.txt

management:
  endpoints:
    web:
      exposure:
        include: health, logfile, metrics
  endpoint:
    health:
      show-details: always
      custom-settings:
        create-new-book-checking-interval: 5

task:
  book:
    auto-create:
      enable: true
      fixed-delay-seconds: 7