spring:
  messages:
    baseName: messages
    encoding: UTF-8
    # Не дает свалиться в системную локаль если не найден файл для переданной в MessageSource
    # Если false то будут браться сообщения из дефолтного файла, если true, то из файла соответствующего системной локали
    fallbackToSystemLocale: false
test:
  min-accept-count: 4
  locale: ru-RU
  file-name-by-locale-tag:
    ru-RU: dao/test-for-students_ru.csv
    en-US: dao/test-for-students.csv
  formatter-properties:
    answer-tabulation:
    answer-arabic-numeration-enable: true
    question-delimiter: ----------------------------------------------------------------------------
